#!/bin/bash

FILE="$1"
Y="$2"
C=$3

# check
test -f "$FILE" || exit 1
rm "${FILE}.new" # just in case

idx=0
IFS=":"

for i in $C; do

[ -z "$i" ] && continue;

if [ "$idx" -eq 0 ]; then
( cat <<_EOT_
/*******************************************************************************
 * Copyright (c) $Y $i and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     $i - initial API and implementation
_EOT_
) >> "${FILE}.new"

else #else

( cat <<_EOT_
 *     $i - additional work
_EOT_
) >> "${FILE}.new"
fi
idx=$[idx+1]
done
( cat <<_EOT_
 *******************************************************************************/
_EOT_
) >> "${FILE}.new"

perl -0777 -pe 's!^/\*(?:.|[\r\n])*?\*/[\r\n]*!!m;' < "$FILE" >> "${FILE}.new"
#rm "$FILE"
#mv "${FILE}.new" "$FILE"
