#!/bin/bash

SD="/home/jens/git/1.1/org.openscada.atlantis"
ES="/home/jens/git/1.2/org.openscada.atlantis"
#ES="/home/jens/Development/workspace_openscada12/org.openscada.atlantis"

S="$PWD/changeHeader"

pushd  "$SD"

for i in `find -name "*.java" -and -type f`
do

start=`git log --format=format:%ai -- "$i" | awk '{ print $1 }' | awk -F- '{ print $1 }' | sort -u | head -1`
end=`git log --format=format:%ai -- "$i" | awk '{ print $1 }' | awk -F- '{ print $1 }' | sort -u | tail -1`

TF="$ES/$n"

egrep "Copyright.*TH4" "$TF" && auth="$auth:TH4 SYSTEMS GmbH"
egrep "Copyright.*Jens Reimann" "$TF" && auth="Jens Reimann"
egrep "Copyright.*Rose" "$TF" && auth="$auth:Jürgen Rose"
egrep "Copyright.*IBH" "$TF" && auth="$auth:IBH SYSTEMS GmbH"

if [ "$start" -eq "$end" ]; then
y="$start"
else
y="$start, $end"
fi

n=`echo $i | sed 's/org\/openscada/org\/eclipse\/scada/'`
n=`echo $n | sed s/org.openscada/org.eclipse.scada/`

if [ -f "$TF" ]; then
echo $i - $n - $y - $c
"$S" "$TF" "$y" "$auth"
fi


done

popd
